### ISSUE TITLE
Webapp Updater failed and flipper stuck

### ISSUE THREAD

**Issue by Yanking7556** [Next-Flip/Momentum-Firmware#200]
### Describe the bug.

attempted updating from Momentum-3 to 6 just now, and webapp failed with 
"890.065c7545.js:1 Updater: RPC error in command 'storage.write': ERROR_STORAGE_INVALID_PARAMETER", 
and followed with, 
890.065c7545.js:1 Updater: RPC error in command 'storage.write': ERROR_CONTINUOUS_COMMAND_INTERRUPTED
890.065c7545.js:1 Updater: storage.write: /ext/update/f7-update-mntm-006/resources.tar.gz
890.065c7545.js:1 Updater: RPC error in command 'storage.write': ERROR_CONTINUOUS_COMMAND_INTERRUPTED

The Flipper said update failed, and now is in a constant rebooting loop of "unsupported radio stack".

Please let me know how I should proceed... 

### Reproduction

Not sure...

### Target

Windows 10, Chrome Version 128.0.6613.113 (Official Build) (64-bit), Flipper MMT-3

### Logs

```Text
`vendor.4e4e859b.js:1 NotFoundError: Failed to execute 'requestPort' on 'Serial': No port selected by the user.
a @ vendor.4e4e859b.js:1
890.065c7545.js:1 Main: Flipper connected
890.065c7545.js:1 Main: RPC started
890.065c7545.js:1 Device: gui.startScreenStreamRequest: OK
890.065c7545.js:1 Main: Fetched device info
41chunk-common.929aa92b.js:1 Uncaught TypeError: Cannot read properties of null (reading 'data')
    at S (chunk-common.929aa92b.js:1:2761)
    at chunk-common.929aa92b.js:1:8178
    at vendor.4e4e859b.js:5:178449
    at Array.forEach (<anonymous>)
    at Object.emit (vendor.4e4e859b.js:5:178437)
    at l.onmessage (chunk-common.929aa92b.js:1:1796)
890.065c7545.js:1 Updater: Update started
890.065c7545.js:1 Device: gui.stopScreenStreamRequest: OK
890.065c7545.js:1 Updater: Region provisioning message: {"countryCode":"CA","bands":[{"start":304100000,"end":321950000,"powerLimit":12,"dutyCycle":50},{"start":433050000,"end":434790000,"powerLimit":12,"dutyCycle":50},{"start":915000000,"end":928000000,"powerLimit":12,"dutyCycle":50}]}
890.065c7545.js:1 Updater: Set Sub-GHz region: CA
890.065c7545.js:1 Updater: Downloaded firmware from https://up.momentum-fw.dev/firmware/mntm-006/flipper-z-f7-update-mntm-006.tgz
890.065c7545.js:1 Updater: Loading firmware files
890.065c7545.js:1 Updater: storage.mkdir: /ext/update/f7-update-mntm-006
890.065c7545.js:1 Updater: storage.write: /ext/update/f7-update-mntm-006/firmware.dfu
890.065c7545.js:1 Updater: storage.write: /ext/update/f7-update-mntm-006/firstboot.bin
890.065c7545.js:1 Updater: RPC error in command 'storage.write': ERROR_STORAGE_INVALID_PARAMETER
log @ 890.065c7545.js:1
890.065c7545.js:1 Updater: storage.write: /ext/update/f7-update-mntm-006/radio.bin
890.065c7545.js:1 Updater: RPC error in command 'storage.write': ERROR_CONTINUOUS_COMMAND_INTERRUPTED
log @ 890.065c7545.js:1
890.065c7545.js:1 Updater: storage.write: /ext/update/f7-update-mntm-006/resources.tar.gz
890.065c7545.js:1 Updater: RPC error in command 'storage.write': ERROR_CONTINUOUS_COMMAND_INTERRUPTED
log @ 890.065c7545.js:1
890.065c7545.js:1 Updater: storage.write: /ext/update/f7-update-mntm-006/splash.bin
890.065c7545.js:1 Updater: storage.write: /ext/update/f7-update-mntm-006/update.fuf
890.065c7545.js:1 Updater: storage.write: /ext/update/f7-update-mntm-006/updater.bin
890.065c7545.js:1 Updater: Loading update manifest
890.065c7545.js:1 Updater: system.update: OK
890.065c7545.js:1 Updater: Rebooting Flipper
890.065c7545.js:1 Main: Flipper has been disconnected
890.065c7545.js:1 Main: Flipper connected
2890.065c7545.js:1 Main: Flipper has been disconnected
890.065c7545.js:1 Main: Flipper connected
890.065c7545.js:1 Main: Flipper has been disconnected
890.065c7545.js:1 Main: Flipper connected`
```

**Comment by Yanking7556** [comment]
I was able to break out of the update loop with qFlipper and a few reboot attempts. I am going to attempt to update via qFlipper and see if that works ok.

**Comment by WillyJL** [comment]
if that fails, please enter dfu mode (hold back and left, release back) and click repair in qflipper. after that, install momentum again

**Comment by Yanking7556** [comment]
> if that fails, please enter dfu mode (hold back and left, release back) and click repair in qflipper. after that, install momentum again

Thank you for the swift reply Willy! The qFlipper app was somehow able to complete the install. I thought maybe my SD card had corrupted somehow....
